name       : kdesu
version    : 5.71.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kdesu-5.71.0.tar.xz : b183e67c089b02f984284b5eb3c05f7216d289bef7ae08a9e6c6f991b2a1a23a
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
optimize   : lto
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
