name       : kdesu
version    : 5.88.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.88/kdesu-5.88.0.tar.xz : 4505e560c6e5504a29f42baaa910b3efee401c4d8b7ed0fc1e2a6e2d776e25fd
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
