name       : kdesu
version    : 5.48.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kdesu-5.48.0.tar.xz : 65133975fa107f4d4f1dd5012748bc9a3b262d5fef27f14f19dbad6e001c6a92
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
