name       : kdesu
version    : 5.91.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/kdesu-5.91.0.tar.xz : 55da7ee8c24e49dfd8ae49e1d006e67f541d35d111df412c5eaa8180784a40f2
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
