name       : kdesu
version    : 5.42.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/kdesu-5.42.0.tar.xz : 1d9e6b497aa5e0eb8fecfa1519185c944af7014f8a9d77af36d3457e60b80210
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
