name       : kdesu
version    : 5.60.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kdesu-5.60.0.tar.xz : 3a040ae9825738d9b4953086d6c262009dcff877a4ed7e6925e3a34086007687
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
