name       : kdesu
version    : 5.67.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kdesu-5.67.0.tar.xz : 0e06f5422b6386b4a9b0ed7211943e73b5c47ba83226f26a91c9b5c4aa01b0ed
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
