name       : kdesu
version    : 5.51.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kdesu-5.51.0.tar.xz : e916884bc64b7d2abaaed1bf42cb711c438516ced6a25d610b5f91ed0c854086
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
