name       : kdesu
version    : 5.64.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kdesu-5.64.0.tar.xz : f4644b0ee91c55473589909c20a7fa1cfbd3d466f1c72b330d53871a2346d4f0
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
