name       : kdesu
version    : 5.109.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/kdesu-5.109.0.tar.xz : fe2300330b49e1c3f35088270c0a03a019ffc17d9ef0b6b3438188ac4850d415
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
