name       : kdesu
version    : 5.32.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/5.32/kdesu-5.32.0.tar.xz : 140ebb81d6c3370785ccefce51aa1575824eab38f2dd79f3676b15bf230c5e7f
license    : LGPL-2.1
component  : programming
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake -DKDESU_USE_SUDO_DEFAULT=ON .
build      : |
    %make
install    : |
    %make_install
