name       : kdesu
version    : 5.55.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kdesu-5.55.0.tar.xz : 0ef404cd3d04676434f3c9d67db902c6aefedc17a95eb195db5db1fbaa954ff4
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
