name       : kdesu
version    : 5.59.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kdesu-5.59.0.tar.xz : 7cf1c31475deb85c1045b48303d424ada6e808d1cb9787b522089793185b6c77
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
