name       : kdesu
version    : 5.36.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.36/kdesu-5.36.0.tar.xz : 8af37b0ca1563c58e5f8446f66286b2d418946960575cf6f444ae314aa198f06
license    : LGPL-2.1
component  : programming
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake -DKDESU_USE_SUDO_DEFAULT=ON .
build      : |
    %make
install    : |
    %make_install
