name       : kdesu
version    : 5.87.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.87/kdesu-5.87.0.tar.xz : 795a4f2a8b7b530dfcd40021d506d0e4e6acd05acf1a7c08704102b0181c6b15
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
