name       : kdesu
version    : 5.100.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/kdesu-5.100.0.tar.xz : 2fd889ad3df827109417abb9e58509f5bd8b06930a0f608ba22892693f0ff6b1
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
