name       : kdesu
version    : 5.77.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/kdesu-5.77.0.tar.xz : bca5d64ab4d3f446c8c42f091b1982a83e80d4b810e0c00b1ae135a9751c632f
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
optimize   : lto
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
