name       : kdesu
version    : 5.35.0
release    : 2
source     :
    - https://download.kde.org/stable/frameworks/5.35/kdesu-5.35.0.tar.xz : 1e1a8a8ff712ab0040a23029cb0eb3cf3e6f9304a1c875473d64d6f840d01db7
license    : LGPL-2.1
component  : programming
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake -DKDESU_USE_SUDO_DEFAULT=ON .
build      : |
    %make
install    : |
    %make_install
