name       : kdesu
version    : 5.99.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.99/kdesu-5.99.0.tar.xz : b393d9de503c2785eb20fe88b21983abf6917e1079b2b2d77341cd6255751c32
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
