name       : kdesu
version    : 5.44.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kdesu-5.44.0.tar.xz : e2e38bf4bf7cc0f2ffb16d2f677f36b930a32ced452a53379d983f6bd999cbdc
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON .
build      : |
    %make
install    : |
    %make_install
