name       : kdesu
version    : 5.83.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kdesu-5.83.0.tar.xz : 9eefd9bf9d77f2af58774adea4c9f875472b03ea7e5064e68e901420d2b41fe3
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
